image: alpine:latest

# We have optionally specified stages of our continuous integration/delivery/deployment process
stages:
  - build
  - test
  - package

# OUTPUT_FILE_NAME and UNUSED_VARIABLE are variables that have been specified
# We may reference them like other shellscript/bash variables i.e. $OUTPUT_FILE_NAME
variables:
  OUTPUT_FILE_NAME: "test.txt"
  UNUSED_VARIABLE: "This variable will not be used"


build: 
  stage: build
  script:
    - echo "Building program"
    - mv math-program.sh math.sh
    - chmod +x math.sh
  artifacts:
    paths:
      - math.sh


test:
  stage: test
  dependencies: 
    - build
  script:
    - ./math.sh 2 3 4
    - if [ 1 -eq `cat $OUTPUT_FILE_NAME | grep "((2 ** 3) + (4 * 3)) = 20" | wc -l` ]; then echo "Test Successful"; else echo "Test failed";exit 100; fi;

package:
  stage: package
  dependencies: 
    - build
    - test
  script:
    - tar -zcvf math.tar.gz math.sh
  artifacts:
    paths:
    - math.tar.gz
